name: Example - Build docker NPM Package

on:
  push:
    branches:
      - main

jobs:
  npm-build:
    if: github.ref == 'refs/heads/main'
    needs: npm-scan
    uses: htaic/.github/.github/workflows/npm-docker-build.yml@main
    with:
      yarn_arg: {{ your yarn arg }}
      # optional
      working_dir: .
      npmtoken_for_docker: false
      trigger_release: false
    secrets: inherit
