name: Example - Scan NPM Package

on:
  push:

jobs:
  npm-scan:
    uses: htaic/.github/.github/workflows/npm-codescan.yml@main
    with:
      # optional
      working_dir: .
      allow_lint: true
      allow_audit: true
    secrets: inherit
