name: Example - Scan NPM Package

on:
  push:

jobs:
  npm-scan:
    uses: htaic/.github/.github/workflows/npm-codescan-complete.yml@main
    with:
      # optional
      working_dir: .
      allow_lint: true
      allow_audit: true
      jest_command: "test"
      playwright: false
      playwright_command: "playwright"
      jira_project_key: ""
    secrets: inherit