name: Generate Terraform documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - config/*
      - deployments/*
      - modules/*
      - scripts/*

jobs:
  terraform-doc:
    if: github.ref == 'refs/heads/main'
    uses: htaic/.github/.github/workflows/terraform-doc.yml@main
    with:
      # optional 
      doc_dir:
      doc_template: 
      commit_msg: 
    secrets: inherit
