name: CPP Codescan

on:
  workflow_call:
    inputs:
      BUILD_WRAPPER_OUT_DIR:
        required: false
        description: "Directory Path of Output"
        type: string
        default: build_wrapper_output_directory
jobs:
  sonar-build:
    name: Sonar Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v1

      - name: Set up Python 3.8 for gcovr
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install gcovr 5.0
        run: |
          pip install gcovr==5.0 # 5.1 is not supported and apt install version also not work

      - name: Get required packages
        run: |
          sudo apt-get update && sudo apt-get upgrade

          sudo apt-get install -y \
            libunwind-dev \
            build-essential \
            cmake \
            curl \
            git \
            liblog4cplus-dev \
            libpq-dev \
            pkg-config \
            postgresql \
            postgresql-contrib \
            wget \
            xz-utils \
            libcurl4-openssl-dev \
            libssl-dev \
            g++ \
            m4 \
            libboost-all-dev \
            libcurl4-openssl-dev \
            lsb-release \
            libssl-dev=1.1.1f-1ubuntu2.16 \
            libevent-dev

            

          git config --global http.sslVerify false
          git fetch --all

          #sudo apt install lsb-release -y
          curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
          sudo apt-get install redis -y

      - name: Get required packages
        run: |
          echo "Run build-wrapper"

          mkdir build
          cd build
          cmake .. -DDCS_CODE_COVERAGE=ON
          build-wrapper-linux-x86-64 --out-dir ${{ inputs.BUILD_WRAPPER_OUT_DIR }} make clean all

          echo "Run unit test"
          cd bin
          ./*est

          cd ..
          cd ..
          echo "Make coverage"
          echo "current path : " $PWD
          gcovr --sonarqube > coverage.xml

      - name: Run sonar-scanner
        id: sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "current path : " $PWD
          sonar-scanner --define sonar.host.url="https://sonarcloud.io" --define sonar.cfamily.build-wrapper-output="build/${{ inputs.BUILD_WRAPPER_OUT_DIR }}" --define sonar.coverageReportPaths="coverage.xml"
